# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dashboard.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGridLayout, QGroupBox, QHBoxLayout, QLCDNumber,
    QLabel, QLineEdit, QMainWindow, QMdiArea,
    QMenuBar, QProgressBar, QPushButton, QSizePolicy,
    QStatusBar, QTabWidget, QWidget)

class Ui_DroidDAQ(object):
    def setupUi(self, DroidDAQ):
        if not DroidDAQ.objectName():
            DroidDAQ.setObjectName(u"DroidDAQ")
        DroidDAQ.resize(1272, 724)
        icon = QIcon()
        icon.addFile(u"assets/logo DroidJaw no text mini.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        DroidDAQ.setWindowIcon(icon)
        self.centralwidget = QWidget(DroidDAQ)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.pushButton_LoadConfig = QPushButton(self.tab)
        self.pushButton_LoadConfig.setObjectName(u"pushButton_LoadConfig")
        self.pushButton_LoadConfig.setGeometry(QRect(40, 10, 111, 31))
        self.pushButton_SaveConfig = QPushButton(self.tab)
        self.pushButton_SaveConfig.setObjectName(u"pushButton_SaveConfig")
        self.pushButton_SaveConfig.setGeometry(QRect(40, 40, 111, 31))
        self.groupBox_SensConfig = QGroupBox(self.tab)
        self.groupBox_SensConfig.setObjectName(u"groupBox_SensConfig")
        self.groupBox_SensConfig.setGeometry(QRect(20, 90, 551, 311))
        self.lineEdit_NameCh1 = QLineEdit(self.groupBox_SensConfig)
        self.lineEdit_NameCh1.setObjectName(u"lineEdit_NameCh1")
        self.lineEdit_NameCh1.setGeometry(QRect(60, 60, 120, 27))
        font = QFont()
        font.setPointSize(12)
        self.lineEdit_NameCh1.setFont(font)
        self.lineEdit_NameCh2 = QLineEdit(self.groupBox_SensConfig)
        self.lineEdit_NameCh2.setObjectName(u"lineEdit_NameCh2")
        self.lineEdit_NameCh2.setGeometry(QRect(60, 90, 120, 27))
        self.lineEdit_NameCh2.setFont(font)
        self.comboBox_UnitSensor08 = QComboBox(self.groupBox_SensConfig)
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.addItem("")
        self.comboBox_UnitSensor08.setObjectName(u"comboBox_UnitSensor08")
        self.comboBox_UnitSensor08.setGeometry(QRect(450, 270, 61, 21))
        font1 = QFont()
        font1.setPointSize(10)
        self.comboBox_UnitSensor08.setFont(font1)
        self.comboBox_UnitCh6 = QComboBox(self.groupBox_SensConfig)
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.addItem("")
        self.comboBox_UnitCh6.setObjectName(u"comboBox_UnitCh6")
        self.comboBox_UnitCh6.setGeometry(QRect(450, 210, 61, 21))
        self.comboBox_UnitCh6.setFont(font1)
        self.comboBox_UnitCh2 = QComboBox(self.groupBox_SensConfig)
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.addItem("")
        self.comboBox_UnitCh2.setObjectName(u"comboBox_UnitCh2")
        self.comboBox_UnitCh2.setGeometry(QRect(450, 90, 61, 21))
        self.comboBox_UnitCh2.setFont(font1)
        self.comboBox_UnitCh5 = QComboBox(self.groupBox_SensConfig)
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.addItem("")
        self.comboBox_UnitCh5.setObjectName(u"comboBox_UnitCh5")
        self.comboBox_UnitCh5.setGeometry(QRect(450, 180, 61, 21))
        self.comboBox_UnitCh5.setFont(font1)
        self.comboBox_UnitCh3 = QComboBox(self.groupBox_SensConfig)
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.addItem("")
        self.comboBox_UnitCh3.setObjectName(u"comboBox_UnitCh3")
        self.comboBox_UnitCh3.setGeometry(QRect(450, 120, 61, 21))
        self.comboBox_UnitCh3.setFont(font1)
        self.comboBox_UnitCh4 = QComboBox(self.groupBox_SensConfig)
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.addItem("")
        self.comboBox_UnitCh4.setObjectName(u"comboBox_UnitCh4")
        self.comboBox_UnitCh4.setGeometry(QRect(450, 150, 61, 21))
        self.comboBox_UnitCh4.setFont(font1)
        self.comboBox_UnitCh7 = QComboBox(self.groupBox_SensConfig)
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.addItem("")
        self.comboBox_UnitCh7.setObjectName(u"comboBox_UnitCh7")
        self.comboBox_UnitCh7.setGeometry(QRect(450, 240, 61, 21))
        self.comboBox_UnitCh7.setFont(font1)
        self.comboBox_UnitCh1 = QComboBox(self.groupBox_SensConfig)
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.addItem("")
        self.comboBox_UnitCh1.setObjectName(u"comboBox_UnitCh1")
        self.comboBox_UnitCh1.setGeometry(QRect(450, 60, 61, 21))
        self.comboBox_UnitCh1.setFont(font1)
        self.lineEdit_NameCh3 = QLineEdit(self.groupBox_SensConfig)
        self.lineEdit_NameCh3.setObjectName(u"lineEdit_NameCh3")
        self.lineEdit_NameCh3.setGeometry(QRect(60, 120, 120, 27))
        self.lineEdit_NameCh3.setFont(font)
        self.lineEdit_NameCh4 = QLineEdit(self.groupBox_SensConfig)
        self.lineEdit_NameCh4.setObjectName(u"lineEdit_NameCh4")
        self.lineEdit_NameCh4.setGeometry(QRect(60, 150, 120, 27))
        self.lineEdit_NameCh4.setFont(font)
        self.lineEdit_NameCh5 = QLineEdit(self.groupBox_SensConfig)
        self.lineEdit_NameCh5.setObjectName(u"lineEdit_NameCh5")
        self.lineEdit_NameCh5.setGeometry(QRect(60, 180, 120, 27))
        self.lineEdit_NameCh5.setFont(font)
        self.lineEdit_NameCh6 = QLineEdit(self.groupBox_SensConfig)
        self.lineEdit_NameCh6.setObjectName(u"lineEdit_NameCh6")
        self.lineEdit_NameCh6.setGeometry(QRect(60, 210, 120, 27))
        self.lineEdit_NameCh6.setFont(font)
        self.lineEdit_NameCh7 = QLineEdit(self.groupBox_SensConfig)
        self.lineEdit_NameCh7.setObjectName(u"lineEdit_NameCh7")
        self.lineEdit_NameCh7.setGeometry(QRect(60, 240, 120, 27))
        self.lineEdit_NameCh7.setFont(font)
        self.lineEdit_NameCh8 = QLineEdit(self.groupBox_SensConfig)
        self.lineEdit_NameCh8.setObjectName(u"lineEdit_NameCh8")
        self.lineEdit_NameCh8.setGeometry(QRect(60, 270, 120, 27))
        self.lineEdit_NameCh8.setFont(font)
        self.lineEdit_CalCh1 = QLineEdit(self.groupBox_SensConfig)
        self.lineEdit_CalCh1.setObjectName(u"lineEdit_CalCh1")
        self.lineEdit_CalCh1.setGeometry(QRect(190, 60, 191, 27))
        self.lineEdit_CalCh1.setFont(font)
        self.lineEdit_CalCh2 = QLineEdit(self.groupBox_SensConfig)
        self.lineEdit_CalCh2.setObjectName(u"lineEdit_CalCh2")
        self.lineEdit_CalCh2.setGeometry(QRect(190, 90, 191, 27))
        self.lineEdit_CalCh2.setFont(font)
        self.lineEdit_CalCh3 = QLineEdit(self.groupBox_SensConfig)
        self.lineEdit_CalCh3.setObjectName(u"lineEdit_CalCh3")
        self.lineEdit_CalCh3.setGeometry(QRect(190, 120, 191, 27))
        self.lineEdit_CalCh3.setFont(font)
        self.lineEdit_CalCh4 = QLineEdit(self.groupBox_SensConfig)
        self.lineEdit_CalCh4.setObjectName(u"lineEdit_CalCh4")
        self.lineEdit_CalCh4.setGeometry(QRect(190, 150, 191, 27))
        self.lineEdit_CalCh4.setFont(font)
        self.lineEdit_CalCh5 = QLineEdit(self.groupBox_SensConfig)
        self.lineEdit_CalCh5.setObjectName(u"lineEdit_CalCh5")
        self.lineEdit_CalCh5.setGeometry(QRect(190, 180, 191, 27))
        self.lineEdit_CalCh5.setFont(font)
        self.lineEdit_CalCh6 = QLineEdit(self.groupBox_SensConfig)
        self.lineEdit_CalCh6.setObjectName(u"lineEdit_CalCh6")
        self.lineEdit_CalCh6.setGeometry(QRect(190, 210, 191, 27))
        self.lineEdit_CalCh6.setFont(font)
        self.lineEdit_CalCh7 = QLineEdit(self.groupBox_SensConfig)
        self.lineEdit_CalCh7.setObjectName(u"lineEdit_CalCh7")
        self.lineEdit_CalCh7.setGeometry(QRect(190, 240, 191, 27))
        self.lineEdit_CalCh7.setFont(font)
        self.lineEdit_CalCh8 = QLineEdit(self.groupBox_SensConfig)
        self.lineEdit_CalCh8.setObjectName(u"lineEdit_CalCh8")
        self.lineEdit_CalCh8.setGeometry(QRect(190, 270, 191, 27))
        self.lineEdit_CalCh8.setFont(font)
        self.label_3 = QLabel(self.groupBox_SensConfig)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 60, 31, 31))
        self.label_6 = QLabel(self.groupBox_SensConfig)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 90, 31, 31))
        self.label_7 = QLabel(self.groupBox_SensConfig)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 120, 31, 31))
        self.label_8 = QLabel(self.groupBox_SensConfig)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 150, 31, 31))
        self.label_9 = QLabel(self.groupBox_SensConfig)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 180, 31, 31))
        self.label_10 = QLabel(self.groupBox_SensConfig)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 210, 31, 31))
        self.label_11 = QLabel(self.groupBox_SensConfig)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(30, 240, 31, 31))
        self.label_12 = QLabel(self.groupBox_SensConfig)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 270, 31, 31))
        self.label_13 = QLabel(self.groupBox_SensConfig)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(60, 30, 121, 31))
        self.label_14 = QLabel(self.groupBox_SensConfig)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(190, 30, 121, 31))
        self.pushButton_BrwsCalCh1 = QPushButton(self.groupBox_SensConfig)
        self.pushButton_BrwsCalCh1.setObjectName(u"pushButton_BrwsCalCh1")
        self.pushButton_BrwsCalCh1.setGeometry(QRect(390, 60, 51, 24))
        self.pushButton_BrwsCalCh2 = QPushButton(self.groupBox_SensConfig)
        self.pushButton_BrwsCalCh2.setObjectName(u"pushButton_BrwsCalCh2")
        self.pushButton_BrwsCalCh2.setGeometry(QRect(390, 90, 51, 24))
        self.pushButton_BrwsCalCh3 = QPushButton(self.groupBox_SensConfig)
        self.pushButton_BrwsCalCh3.setObjectName(u"pushButton_BrwsCalCh3")
        self.pushButton_BrwsCalCh3.setGeometry(QRect(390, 120, 51, 24))
        self.pushButton_BrwsCalCh4 = QPushButton(self.groupBox_SensConfig)
        self.pushButton_BrwsCalCh4.setObjectName(u"pushButton_BrwsCalCh4")
        self.pushButton_BrwsCalCh4.setGeometry(QRect(390, 150, 51, 24))
        self.pushButton_BrwsCalCh5 = QPushButton(self.groupBox_SensConfig)
        self.pushButton_BrwsCalCh5.setObjectName(u"pushButton_BrwsCalCh5")
        self.pushButton_BrwsCalCh5.setGeometry(QRect(390, 180, 51, 24))
        self.pushButton_BrwsCalCh6 = QPushButton(self.groupBox_SensConfig)
        self.pushButton_BrwsCalCh6.setObjectName(u"pushButton_BrwsCalCh6")
        self.pushButton_BrwsCalCh6.setGeometry(QRect(390, 210, 51, 24))
        self.pushButton_BrwsCalCh7 = QPushButton(self.groupBox_SensConfig)
        self.pushButton_BrwsCalCh7.setObjectName(u"pushButton_BrwsCalCh7")
        self.pushButton_BrwsCalCh7.setGeometry(QRect(390, 240, 51, 24))
        self.pushButton_BrwsCalCh8 = QPushButton(self.groupBox_SensConfig)
        self.pushButton_BrwsCalCh8.setObjectName(u"pushButton_BrwsCalCh8")
        self.pushButton_BrwsCalCh8.setGeometry(QRect(390, 270, 51, 24))
        self.label_16 = QLabel(self.groupBox_SensConfig)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(450, 30, 61, 21))
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.comboBox_ComPort = QComboBox(self.tab)
        self.comboBox_ComPort.addItem("")
        self.comboBox_ComPort.addItem("")
        self.comboBox_ComPort.addItem("")
        self.comboBox_ComPort.addItem("")
        self.comboBox_ComPort.addItem("")
        self.comboBox_ComPort.addItem("")
        self.comboBox_ComPort.addItem("")
        self.comboBox_ComPort.addItem("")
        self.comboBox_ComPort.addItem("")
        self.comboBox_ComPort.addItem("")
        self.comboBox_ComPort.setObjectName(u"comboBox_ComPort")
        self.comboBox_ComPort.setGeometry(QRect(380, 20, 51, 31))
        self.comboBox_ComPort.setFont(font)
        self.label_15 = QLabel(self.tab)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(250, 20, 121, 31))
        self.label_15.setFont(font)
        self.pushButton_ApplyConfig = QPushButton(self.tab)
        self.pushButton_ApplyConfig.setObjectName(u"pushButton_ApplyConfig")
        self.pushButton_ApplyConfig.setGeometry(QRect(630, 10, 81, 31))
        self.pushButton_ApplyConfig.setFont(font)
        self.comboBox_FreqSampl = QComboBox(self.tab)
        self.comboBox_FreqSampl.addItem("")
        self.comboBox_FreqSampl.addItem("")
        self.comboBox_FreqSampl.addItem("")
        self.comboBox_FreqSampl.addItem("")
        self.comboBox_FreqSampl.addItem("")
        self.comboBox_FreqSampl.addItem("")
        self.comboBox_FreqSampl.addItem("")
        self.comboBox_FreqSampl.addItem("")
        self.comboBox_FreqSampl.addItem("")
        self.comboBox_FreqSampl.addItem("")
        self.comboBox_FreqSampl.addItem("")
        self.comboBox_FreqSampl.setObjectName(u"comboBox_FreqSampl")
        self.comboBox_FreqSampl.setGeometry(QRect(380, 50, 51, 31))
        self.comboBox_FreqSampl.setFont(font)
        self.label_17 = QLabel(self.tab)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(190, 50, 181, 31))
        self.label_17.setFont(font)
        self.pushButton_Scan = QPushButton(self.tab)
        self.pushButton_Scan.setObjectName(u"pushButton_Scan")
        self.pushButton_Scan.setGeometry(QRect(450, 20, 51, 31))
        self.tabWidget.addTab(self.tab, "")
        self.DataAcquisition = QWidget()
        self.DataAcquisition.setObjectName(u"DataAcquisition")
        self.groupBoxSensorA = QGroupBox(self.DataAcquisition)
        self.groupBoxSensorA.setObjectName(u"groupBoxSensorA")
        self.groupBoxSensorA.setGeometry(QRect(10, 150, 371, 441))
        self.layoutWidget = QWidget(self.groupBoxSensorA)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 17, 141, 41))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.checkBox_Ch1 = QCheckBox(self.layoutWidget)
        self.checkBox_Ch1.setObjectName(u"checkBox_Ch1")

        self.horizontalLayout.addWidget(self.checkBox_Ch1)

        self.label_NameCh1 = QLabel(self.layoutWidget)
        self.label_NameCh1.setObjectName(u"label_NameCh1")
        font2 = QFont()
        font2.setPointSize(14)
        font2.setBold(True)
        self.label_NameCh1.setFont(font2)

        self.horizontalLayout.addWidget(self.label_NameCh1)

        self.layoutWidget1 = QWidget(self.groupBoxSensorA)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(10, 70, 141, 41))
        self.horizontalLayout_2 = QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.checkBox_Ch2 = QCheckBox(self.layoutWidget1)
        self.checkBox_Ch2.setObjectName(u"checkBox_Ch2")

        self.horizontalLayout_2.addWidget(self.checkBox_Ch2)

        self.label_NameCh2 = QLabel(self.layoutWidget1)
        self.label_NameCh2.setObjectName(u"label_NameCh2")
        self.label_NameCh2.setFont(font2)

        self.horizontalLayout_2.addWidget(self.label_NameCh2)

        self.layoutWidget2 = QWidget(self.groupBoxSensorA)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(10, 120, 141, 41))
        self.horizontalLayout_3 = QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.checkBox_Ch3 = QCheckBox(self.layoutWidget2)
        self.checkBox_Ch3.setObjectName(u"checkBox_Ch3")

        self.horizontalLayout_3.addWidget(self.checkBox_Ch3)

        self.label_NameCh3 = QLabel(self.layoutWidget2)
        self.label_NameCh3.setObjectName(u"label_NameCh3")
        self.label_NameCh3.setFont(font2)

        self.horizontalLayout_3.addWidget(self.label_NameCh3)

        self.layoutWidget3 = QWidget(self.groupBoxSensorA)
        self.layoutWidget3.setObjectName(u"layoutWidget3")
        self.layoutWidget3.setGeometry(QRect(10, 168, 141, 41))
        self.horizontalLayout_4 = QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.checkBox_Ch4 = QCheckBox(self.layoutWidget3)
        self.checkBox_Ch4.setObjectName(u"checkBox_Ch4")

        self.horizontalLayout_4.addWidget(self.checkBox_Ch4)

        self.label_NameCh4 = QLabel(self.layoutWidget3)
        self.label_NameCh4.setObjectName(u"label_NameCh4")
        self.label_NameCh4.setFont(font2)

        self.horizontalLayout_4.addWidget(self.label_NameCh4)

        self.lcdNumber_Ch1 = QLCDNumber(self.groupBoxSensorA)
        self.lcdNumber_Ch1.setObjectName(u"lcdNumber_Ch1")
        self.lcdNumber_Ch1.setGeometry(QRect(160, 20, 141, 41))
        font3 = QFont()
        font3.setFamilies([u"SimSun"])
        font3.setPointSize(28)
        font3.setBold(False)
        font3.setKerning(True)
        self.lcdNumber_Ch1.setFont(font3)
        self.lcdNumber_Ch1.setStyleSheet(u"QLCDNumber {\n"
"    background-color: #d3d3d3; /* Warna abu-abu terang */\n"
"    color: #000000;            /* Warna angka hitam */\n"
"    border: 1px solid #8f8f8f; /* Garis tepi agar lebih tegas */\n"
"    border-radius: 4px;        /* Membuat sudut sedikit melengkung */\n"
"}")
        self.lcdNumber_Ch1.setFrameShape(QFrame.Shape.StyledPanel)
        self.lcdNumber_Ch1.setFrameShadow(QFrame.Shadow.Raised)
        self.lcdNumber_Ch1.setSmallDecimalPoint(True)
        self.lcdNumber_Ch1.setDigitCount(3)
        self.lcdNumber_Ch1.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.lcdNumber_Ch1.setProperty(u"value", 0.000000000000000)
        self.lcdNumber_Ch2 = QLCDNumber(self.groupBoxSensorA)
        self.lcdNumber_Ch2.setObjectName(u"lcdNumber_Ch2")
        self.lcdNumber_Ch2.setGeometry(QRect(160, 70, 141, 41))
        self.lcdNumber_Ch2.setFont(font3)
        self.lcdNumber_Ch2.setStyleSheet(u"QLCDNumber {\n"
"    background-color: #d3d3d3; /* Warna abu-abu terang */\n"
"    color: #000000;            /* Warna angka hitam */\n"
"    border: 1px solid #8f8f8f; /* Garis tepi agar lebih tegas */\n"
"    border-radius: 4px;        /* Membuat sudut sedikit melengkung */\n"
"}")
        self.lcdNumber_Ch2.setFrameShape(QFrame.Shape.StyledPanel)
        self.lcdNumber_Ch2.setFrameShadow(QFrame.Shadow.Raised)
        self.lcdNumber_Ch2.setSmallDecimalPoint(True)
        self.lcdNumber_Ch2.setDigitCount(3)
        self.lcdNumber_Ch2.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.lcdNumber_Ch2.setProperty(u"value", 0.000000000000000)
        self.lcdNumber_Ch3 = QLCDNumber(self.groupBoxSensorA)
        self.lcdNumber_Ch3.setObjectName(u"lcdNumber_Ch3")
        self.lcdNumber_Ch3.setGeometry(QRect(160, 120, 141, 41))
        self.lcdNumber_Ch3.setFont(font3)
        self.lcdNumber_Ch3.setStyleSheet(u"QLCDNumber {\n"
"    background-color: #d3d3d3; /* Warna abu-abu terang */\n"
"    color: #000000;            /* Warna angka hitam */\n"
"    border: 1px solid #8f8f8f; /* Garis tepi agar lebih tegas */\n"
"    border-radius: 4px;        /* Membuat sudut sedikit melengkung */\n"
"}")
        self.lcdNumber_Ch3.setFrameShape(QFrame.Shape.StyledPanel)
        self.lcdNumber_Ch3.setFrameShadow(QFrame.Shadow.Raised)
        self.lcdNumber_Ch3.setSmallDecimalPoint(True)
        self.lcdNumber_Ch3.setDigitCount(3)
        self.lcdNumber_Ch3.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.lcdNumber_Ch3.setProperty(u"value", 0.000000000000000)
        self.lcdNumber_Ch4 = QLCDNumber(self.groupBoxSensorA)
        self.lcdNumber_Ch4.setObjectName(u"lcdNumber_Ch4")
        self.lcdNumber_Ch4.setGeometry(QRect(160, 170, 141, 41))
        self.lcdNumber_Ch4.setFont(font3)
        self.lcdNumber_Ch4.setStyleSheet(u"QLCDNumber {\n"
"    background-color: #d3d3d3; /* Warna abu-abu terang */\n"
"    color: #000000;            /* Warna angka hitam */\n"
"    border: 1px solid #8f8f8f; /* Garis tepi agar lebih tegas */\n"
"    border-radius: 4px;        /* Membuat sudut sedikit melengkung */\n"
"}")
        self.lcdNumber_Ch4.setFrameShape(QFrame.Shape.StyledPanel)
        self.lcdNumber_Ch4.setFrameShadow(QFrame.Shadow.Raised)
        self.lcdNumber_Ch4.setSmallDecimalPoint(True)
        self.lcdNumber_Ch4.setDigitCount(3)
        self.lcdNumber_Ch4.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.lcdNumber_Ch4.setProperty(u"value", 0.000000000000000)
        self.label_UnitCh01 = QLabel(self.groupBoxSensorA)
        self.label_UnitCh01.setObjectName(u"label_UnitCh01")
        self.label_UnitCh01.setGeometry(QRect(300, 20, 61, 41))
        font4 = QFont()
        font4.setPointSize(12)
        font4.setBold(True)
        self.label_UnitCh01.setFont(font4)
        self.label_UnitCh01.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_UnitCh02 = QLabel(self.groupBoxSensorA)
        self.label_UnitCh02.setObjectName(u"label_UnitCh02")
        self.label_UnitCh02.setGeometry(QRect(300, 70, 61, 41))
        self.label_UnitCh02.setFont(font4)
        self.label_UnitCh02.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_UnitCh03 = QLabel(self.groupBoxSensorA)
        self.label_UnitCh03.setObjectName(u"label_UnitCh03")
        self.label_UnitCh03.setGeometry(QRect(300, 120, 61, 41))
        self.label_UnitCh03.setFont(font4)
        self.label_UnitCh03.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_UnitCh04 = QLabel(self.groupBoxSensorA)
        self.label_UnitCh04.setObjectName(u"label_UnitCh04")
        self.label_UnitCh04.setGeometry(QRect(300, 170, 61, 41))
        self.label_UnitCh04.setFont(font4)
        self.label_UnitCh04.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_UnitCh05 = QLabel(self.groupBoxSensorA)
        self.label_UnitCh05.setObjectName(u"label_UnitCh05")
        self.label_UnitCh05.setGeometry(QRect(300, 220, 61, 41))
        self.label_UnitCh05.setFont(font4)
        self.label_UnitCh05.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.layoutWidget4 = QWidget(self.groupBoxSensorA)
        self.layoutWidget4.setObjectName(u"layoutWidget4")
        self.layoutWidget4.setGeometry(QRect(10, 220, 141, 41))
        self.horizontalLayout_5 = QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.checkBox_Ch5 = QCheckBox(self.layoutWidget4)
        self.checkBox_Ch5.setObjectName(u"checkBox_Ch5")

        self.horizontalLayout_5.addWidget(self.checkBox_Ch5)

        self.label_NameCh5 = QLabel(self.layoutWidget4)
        self.label_NameCh5.setObjectName(u"label_NameCh5")
        self.label_NameCh5.setFont(font2)

        self.horizontalLayout_5.addWidget(self.label_NameCh5)

        self.lcdNumber_Ch5 = QLCDNumber(self.groupBoxSensorA)
        self.lcdNumber_Ch5.setObjectName(u"lcdNumber_Ch5")
        self.lcdNumber_Ch5.setGeometry(QRect(160, 220, 141, 41))
        self.lcdNumber_Ch5.setFont(font3)
        self.lcdNumber_Ch5.setStyleSheet(u"QLCDNumber {\n"
"    background-color: #d3d3d3; /* Warna abu-abu terang */\n"
"    color: #000000;            /* Warna angka hitam */\n"
"    border: 1px solid #8f8f8f; /* Garis tepi agar lebih tegas */\n"
"    border-radius: 4px;        /* Membuat sudut sedikit melengkung */\n"
"}")
        self.lcdNumber_Ch5.setFrameShape(QFrame.Shape.StyledPanel)
        self.lcdNumber_Ch5.setFrameShadow(QFrame.Shadow.Raised)
        self.lcdNumber_Ch5.setSmallDecimalPoint(True)
        self.lcdNumber_Ch5.setDigitCount(3)
        self.lcdNumber_Ch5.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.lcdNumber_Ch5.setProperty(u"value", 0.000000000000000)
        self.label_UnitCh06 = QLabel(self.groupBoxSensorA)
        self.label_UnitCh06.setObjectName(u"label_UnitCh06")
        self.label_UnitCh06.setGeometry(QRect(300, 270, 61, 41))
        self.label_UnitCh06.setFont(font4)
        self.label_UnitCh06.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.layoutWidget5 = QWidget(self.groupBoxSensorA)
        self.layoutWidget5.setObjectName(u"layoutWidget5")
        self.layoutWidget5.setGeometry(QRect(10, 270, 141, 41))
        self.horizontalLayout_6 = QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.checkBox_Ch6 = QCheckBox(self.layoutWidget5)
        self.checkBox_Ch6.setObjectName(u"checkBox_Ch6")

        self.horizontalLayout_6.addWidget(self.checkBox_Ch6)

        self.label_NameCh6 = QLabel(self.layoutWidget5)
        self.label_NameCh6.setObjectName(u"label_NameCh6")
        self.label_NameCh6.setFont(font2)

        self.horizontalLayout_6.addWidget(self.label_NameCh6)

        self.lcdNumber_Ch6 = QLCDNumber(self.groupBoxSensorA)
        self.lcdNumber_Ch6.setObjectName(u"lcdNumber_Ch6")
        self.lcdNumber_Ch6.setGeometry(QRect(160, 270, 141, 41))
        self.lcdNumber_Ch6.setFont(font3)
        self.lcdNumber_Ch6.setStyleSheet(u"QLCDNumber {\n"
"    background-color: #d3d3d3; /* Warna abu-abu terang */\n"
"    color: #000000;            /* Warna angka hitam */\n"
"    border: 1px solid #8f8f8f; /* Garis tepi agar lebih tegas */\n"
"    border-radius: 4px;        /* Membuat sudut sedikit melengkung */\n"
"}")
        self.lcdNumber_Ch6.setFrameShape(QFrame.Shape.StyledPanel)
        self.lcdNumber_Ch6.setFrameShadow(QFrame.Shadow.Raised)
        self.lcdNumber_Ch6.setSmallDecimalPoint(True)
        self.lcdNumber_Ch6.setDigitCount(3)
        self.lcdNumber_Ch6.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.lcdNumber_Ch6.setProperty(u"value", 0.000000000000000)
        self.layoutWidget_2 = QWidget(self.groupBoxSensorA)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(10, 320, 141, 41))
        self.horizontalLayout_9 = QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.checkBox_Ch7 = QCheckBox(self.layoutWidget_2)
        self.checkBox_Ch7.setObjectName(u"checkBox_Ch7")

        self.horizontalLayout_9.addWidget(self.checkBox_Ch7)

        self.label_NameCh7 = QLabel(self.layoutWidget_2)
        self.label_NameCh7.setObjectName(u"label_NameCh7")
        self.label_NameCh7.setFont(font2)

        self.horizontalLayout_9.addWidget(self.label_NameCh7)

        self.label_UnitCh07 = QLabel(self.groupBoxSensorA)
        self.label_UnitCh07.setObjectName(u"label_UnitCh07")
        self.label_UnitCh07.setGeometry(QRect(300, 320, 61, 41))
        self.label_UnitCh07.setFont(font4)
        self.label_UnitCh07.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lcdNumber_Ch7 = QLCDNumber(self.groupBoxSensorA)
        self.lcdNumber_Ch7.setObjectName(u"lcdNumber_Ch7")
        self.lcdNumber_Ch7.setGeometry(QRect(160, 320, 141, 41))
        self.lcdNumber_Ch7.setFont(font3)
        self.lcdNumber_Ch7.setStyleSheet(u"QLCDNumber {\n"
"    background-color: #d3d3d3; /* Warna abu-abu terang */\n"
"    color: #000000;            /* Warna angka hitam */\n"
"    border: 1px solid #8f8f8f; /* Garis tepi agar lebih tegas */\n"
"    border-radius: 4px;        /* Membuat sudut sedikit melengkung */\n"
"}")
        self.lcdNumber_Ch7.setFrameShape(QFrame.Shape.StyledPanel)
        self.lcdNumber_Ch7.setFrameShadow(QFrame.Shadow.Raised)
        self.lcdNumber_Ch7.setSmallDecimalPoint(True)
        self.lcdNumber_Ch7.setDigitCount(3)
        self.lcdNumber_Ch7.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.lcdNumber_Ch7.setProperty(u"value", 0.000000000000000)
        self.label_UnitCh08 = QLabel(self.groupBoxSensorA)
        self.label_UnitCh08.setObjectName(u"label_UnitCh08")
        self.label_UnitCh08.setGeometry(QRect(300, 370, 61, 41))
        self.label_UnitCh08.setFont(font4)
        self.label_UnitCh08.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.layoutWidget_3 = QWidget(self.groupBoxSensorA)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(10, 370, 141, 41))
        self.horizontalLayout_8 = QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.checkBox_Ch8 = QCheckBox(self.layoutWidget_3)
        self.checkBox_Ch8.setObjectName(u"checkBox_Ch8")

        self.horizontalLayout_8.addWidget(self.checkBox_Ch8)

        self.label_NameCh8 = QLabel(self.layoutWidget_3)
        self.label_NameCh8.setObjectName(u"label_NameCh8")
        self.label_NameCh8.setFont(font2)

        self.horizontalLayout_8.addWidget(self.label_NameCh8)

        self.lcdNumber_Ch8 = QLCDNumber(self.groupBoxSensorA)
        self.lcdNumber_Ch8.setObjectName(u"lcdNumber_Ch8")
        self.lcdNumber_Ch8.setGeometry(QRect(160, 370, 141, 41))
        self.lcdNumber_Ch8.setFont(font3)
        self.lcdNumber_Ch8.setStyleSheet(u"QLCDNumber {\n"
"    background-color: #d3d3d3; /* Warna abu-abu terang */\n"
"    color: #000000;            /* Warna angka hitam */\n"
"    border: 1px solid #8f8f8f; /* Garis tepi agar lebih tegas */\n"
"    border-radius: 4px;        /* Membuat sudut sedikit melengkung */\n"
"}")
        self.lcdNumber_Ch8.setFrameShape(QFrame.Shape.StyledPanel)
        self.lcdNumber_Ch8.setFrameShadow(QFrame.Shadow.Raised)
        self.lcdNumber_Ch8.setSmallDecimalPoint(True)
        self.lcdNumber_Ch8.setDigitCount(3)
        self.lcdNumber_Ch8.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.lcdNumber_Ch8.setProperty(u"value", 0.000000000000000)
        self.frame = QFrame(self.DataAcquisition)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 30, 141, 81))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 10, 141, 26))
        font5 = QFont()
        font5.setPointSize(14)
        self.label_2.setFont(font5)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pushButton_Connect = QPushButton(self.frame)
        self.pushButton_Connect.setObjectName(u"pushButton_Connect")
        self.pushButton_Connect.setGeometry(QRect(2, 42, 131, 29))
        self.pushButton_Connect.setFont(font5)
        self.groupBox = QGroupBox(self.DataAcquisition)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(160, 0, 611, 151))
        self.lineEdit_TestName = QLineEdit(self.groupBox)
        self.lineEdit_TestName.setObjectName(u"lineEdit_TestName")
        self.lineEdit_TestName.setGeometry(QRect(120, 20, 371, 22))
        self.lineEdit_TestName.setFont(font)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 81, 16))
        self.label.setFont(font4)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 50, 81, 16))
        self.label_4.setFont(font4)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 80, 91, 21))
        self.label_5.setFont(font4)
        self.lineEdit_TestFolder = QLineEdit(self.groupBox)
        self.lineEdit_TestFolder.setObjectName(u"lineEdit_TestFolder")
        self.lineEdit_TestFolder.setGeometry(QRect(120, 50, 311, 22))
        self.lineEdit_TestFolder.setFont(font)
        self.lineEdit_TestFolder.setReadOnly(True)
        self.pushButton_TestBrowse = QPushButton(self.groupBox)
        self.pushButton_TestBrowse.setObjectName(u"pushButton_TestBrowse")
        self.pushButton_TestBrowse.setGeometry(QRect(440, 50, 51, 24))
        self.lineEdit_TestDuration = QLineEdit(self.groupBox)
        self.lineEdit_TestDuration.setObjectName(u"lineEdit_TestDuration")
        self.lineEdit_TestDuration.setGeometry(QRect(120, 80, 61, 22))
        self.lineEdit_TestDuration.setFont(font)
        self.lineEdit_TestDuration.setReadOnly(True)
        self.pushButton_StartRecord = QPushButton(self.groupBox)
        self.pushButton_StartRecord.setObjectName(u"pushButton_StartRecord")
        self.pushButton_StartRecord.setGeometry(QRect(500, 20, 100, 50))
        self.pushButton_StartRecord.setStyleSheet(u"QPushButton {\n"
"    /* Gradien untuk efek pencahayaan dari atas ke bawah */\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #34e89e, stop:1 #27ae60);\n"
"    \n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"\n"
"    /* Bentuk setengah lingkaran atas (asumsi lebar 100px) */\n"
"    border-top-left-radius: 50px;\n"
"    border-top-right-radius: 50px;\n"
"\n"
"    /* Efek 3D: Garis terang di atas, bayangan gelap di bawah */\n"
"    border-top: 2px solid #a8ff78;\n"
"    border-bottom: 4px solid #1a5e3a; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #40ffaf, stop:1 #2ecc71);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* Efek tombol tertekan: Hilangkan bayangan bawah, tambah padding */\n"
"    border-bottom: 1px solid #1a5e3a;\n"
"    padding-top: 4px;\n"
"}")
        self.pushButton_STOP = QPushButton(self.groupBox)
        self.pushButton_STOP.setObjectName(u"pushButton_STOP")
        self.pushButton_STOP.setGeometry(QRect(500, 70, 101, 51))
        self.pushButton_STOP.setStyleSheet(u"QPushButton {\n"
"    /* Gradien Merah */\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #ff5f6d, stop:1 #e74c3c);\n"
"    \n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"\n"
"    /* Bentuk setengah lingkaran bawah (asumsi lebar 100px) */\n"
"    border-bottom-left-radius: 50px;\n"
"    border-bottom-right-radius: 50px;\n"
"\n"
"    /* Efek 3D: Garis terang tipis di atas, bayangan tebal di bawah */\n"
"    border-top: 1px solid #ff9a9e;\n"
"    border-bottom: 5px solid #96281b;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #ff6b6b, stop:1 #ff4757);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-bottom: 1px solid #96281b;\n"
"    padding-top: 4px;\n"
"}")
        self.progressBar = QProgressBar(self.groupBox)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(120, 120, 391, 23))
        self.progressBar.setValue(24)
        self.mdiArea = QMdiArea(self.DataAcquisition)
        self.mdiArea.setObjectName(u"mdiArea")
        self.mdiArea.setGeometry(QRect(390, 160, 851, 471))
        self.tabWidget.addTab(self.DataAcquisition, "")
        self.Calibration = QWidget()
        self.Calibration.setObjectName(u"Calibration")
        self.tabWidget.addTab(self.Calibration, "")

        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)

        DroidDAQ.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(DroidDAQ)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1272, 22))
        DroidDAQ.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(DroidDAQ)
        self.statusbar.setObjectName(u"statusbar")
        DroidDAQ.setStatusBar(self.statusbar)

        self.retranslateUi(DroidDAQ)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(DroidDAQ)
    # setupUi

    def retranslateUi(self, DroidDAQ):
        DroidDAQ.setWindowTitle(QCoreApplication.translate("DroidDAQ", u"DroidDAQ", None))
        self.pushButton_LoadConfig.setText(QCoreApplication.translate("DroidDAQ", u"Load Config", None))
        self.pushButton_SaveConfig.setText(QCoreApplication.translate("DroidDAQ", u"Save Config", None))
        self.groupBox_SensConfig.setTitle(QCoreApplication.translate("DroidDAQ", u"Sensor Config", None))
        self.lineEdit_NameCh1.setText(QCoreApplication.translate("DroidDAQ", u"Senso01", None))
        self.lineEdit_NameCh2.setText(QCoreApplication.translate("DroidDAQ", u"Sens02", None))
        self.comboBox_UnitSensor08.setItemText(0, QCoreApplication.translate("DroidDAQ", u"N", None))
        self.comboBox_UnitSensor08.setItemText(1, QCoreApplication.translate("DroidDAQ", u"kN", None))
        self.comboBox_UnitSensor08.setItemText(2, QCoreApplication.translate("DroidDAQ", u"g", None))
        self.comboBox_UnitSensor08.setItemText(3, QCoreApplication.translate("DroidDAQ", u"kg", None))
        self.comboBox_UnitSensor08.setItemText(4, QCoreApplication.translate("DroidDAQ", u"ton", None))
        self.comboBox_UnitSensor08.setItemText(5, QCoreApplication.translate("DroidDAQ", u"Pa", None))
        self.comboBox_UnitSensor08.setItemText(6, QCoreApplication.translate("DroidDAQ", u"kPa", None))
        self.comboBox_UnitSensor08.setItemText(7, QCoreApplication.translate("DroidDAQ", u"MPa", None))
        self.comboBox_UnitSensor08.setItemText(8, QCoreApplication.translate("DroidDAQ", u"bar", None))
        self.comboBox_UnitSensor08.setItemText(9, QCoreApplication.translate("DroidDAQ", u"mbar", None))
        self.comboBox_UnitSensor08.setItemText(10, QCoreApplication.translate("DroidDAQ", u"psi", None))
        self.comboBox_UnitSensor08.setItemText(11, QCoreApplication.translate("DroidDAQ", u"atm", None))
        self.comboBox_UnitSensor08.setItemText(12, QCoreApplication.translate("DroidDAQ", u"m", None))
        self.comboBox_UnitSensor08.setItemText(13, QCoreApplication.translate("DroidDAQ", u"cm", None))
        self.comboBox_UnitSensor08.setItemText(14, QCoreApplication.translate("DroidDAQ", u"mm", None))
        self.comboBox_UnitSensor08.setItemText(15, QCoreApplication.translate("DroidDAQ", u"\u03b5", None))
        self.comboBox_UnitSensor08.setItemText(16, QCoreApplication.translate("DroidDAQ", u"\u00b5\u03b5", None))
        self.comboBox_UnitSensor08.setItemText(17, QCoreApplication.translate("DroidDAQ", u"%", None))
        self.comboBox_UnitSensor08.setItemText(18, QCoreApplication.translate("DroidDAQ", u"m/s", None))
        self.comboBox_UnitSensor08.setItemText(19, QCoreApplication.translate("DroidDAQ", u"km/h", None))
        self.comboBox_UnitSensor08.setItemText(20, QCoreApplication.translate("DroidDAQ", u"knots", None))
        self.comboBox_UnitSensor08.setItemText(21, QCoreApplication.translate("DroidDAQ", u"RPM", None))
        self.comboBox_UnitSensor08.setItemText(22, QCoreApplication.translate("DroidDAQ", u"rad/s", None))
        self.comboBox_UnitSensor08.setItemText(23, QCoreApplication.translate("DroidDAQ", u"\u00b0/s", None))
        self.comboBox_UnitSensor08.setItemText(24, QCoreApplication.translate("DroidDAQ", u"Hz", None))
        self.comboBox_UnitSensor08.setItemText(25, QCoreApplication.translate("DroidDAQ", u"V", None))
        self.comboBox_UnitSensor08.setItemText(26, QCoreApplication.translate("DroidDAQ", u"mV", None))
        self.comboBox_UnitSensor08.setItemText(27, QCoreApplication.translate("DroidDAQ", u"A", None))
        self.comboBox_UnitSensor08.setItemText(28, QCoreApplication.translate("DroidDAQ", u"mA", None))
        self.comboBox_UnitSensor08.setItemText(29, QCoreApplication.translate("DroidDAQ", u"W", None))
        self.comboBox_UnitSensor08.setItemText(30, QCoreApplication.translate("DroidDAQ", u"VA", None))
        self.comboBox_UnitSensor08.setItemText(31, QCoreApplication.translate("DroidDAQ", u"VAR", None))
        self.comboBox_UnitSensor08.setItemText(32, QCoreApplication.translate("DroidDAQ", u"kWh", None))

        self.comboBox_UnitSensor08.setCurrentText(QCoreApplication.translate("DroidDAQ", u"N", None))
        self.comboBox_UnitCh6.setItemText(0, QCoreApplication.translate("DroidDAQ", u"N", None))
        self.comboBox_UnitCh6.setItemText(1, QCoreApplication.translate("DroidDAQ", u"kN", None))
        self.comboBox_UnitCh6.setItemText(2, QCoreApplication.translate("DroidDAQ", u"g", None))
        self.comboBox_UnitCh6.setItemText(3, QCoreApplication.translate("DroidDAQ", u"kg", None))
        self.comboBox_UnitCh6.setItemText(4, QCoreApplication.translate("DroidDAQ", u"ton", None))
        self.comboBox_UnitCh6.setItemText(5, QCoreApplication.translate("DroidDAQ", u"Pa", None))
        self.comboBox_UnitCh6.setItemText(6, QCoreApplication.translate("DroidDAQ", u"kPa", None))
        self.comboBox_UnitCh6.setItemText(7, QCoreApplication.translate("DroidDAQ", u"MPa", None))
        self.comboBox_UnitCh6.setItemText(8, QCoreApplication.translate("DroidDAQ", u"bar", None))
        self.comboBox_UnitCh6.setItemText(9, QCoreApplication.translate("DroidDAQ", u"mbar", None))
        self.comboBox_UnitCh6.setItemText(10, QCoreApplication.translate("DroidDAQ", u"psi", None))
        self.comboBox_UnitCh6.setItemText(11, QCoreApplication.translate("DroidDAQ", u"atm", None))
        self.comboBox_UnitCh6.setItemText(12, QCoreApplication.translate("DroidDAQ", u"m", None))
        self.comboBox_UnitCh6.setItemText(13, QCoreApplication.translate("DroidDAQ", u"cm", None))
        self.comboBox_UnitCh6.setItemText(14, QCoreApplication.translate("DroidDAQ", u"mm", None))
        self.comboBox_UnitCh6.setItemText(15, QCoreApplication.translate("DroidDAQ", u"\u03b5", None))
        self.comboBox_UnitCh6.setItemText(16, QCoreApplication.translate("DroidDAQ", u"\u00b5\u03b5", None))
        self.comboBox_UnitCh6.setItemText(17, QCoreApplication.translate("DroidDAQ", u"%", None))
        self.comboBox_UnitCh6.setItemText(18, QCoreApplication.translate("DroidDAQ", u"m/s", None))
        self.comboBox_UnitCh6.setItemText(19, QCoreApplication.translate("DroidDAQ", u"km/h", None))
        self.comboBox_UnitCh6.setItemText(20, QCoreApplication.translate("DroidDAQ", u"knots", None))
        self.comboBox_UnitCh6.setItemText(21, QCoreApplication.translate("DroidDAQ", u"RPM", None))
        self.comboBox_UnitCh6.setItemText(22, QCoreApplication.translate("DroidDAQ", u"rad/s", None))
        self.comboBox_UnitCh6.setItemText(23, QCoreApplication.translate("DroidDAQ", u"\u00b0/s", None))
        self.comboBox_UnitCh6.setItemText(24, QCoreApplication.translate("DroidDAQ", u"Hz", None))
        self.comboBox_UnitCh6.setItemText(25, QCoreApplication.translate("DroidDAQ", u"V", None))
        self.comboBox_UnitCh6.setItemText(26, QCoreApplication.translate("DroidDAQ", u"mV", None))
        self.comboBox_UnitCh6.setItemText(27, QCoreApplication.translate("DroidDAQ", u"A", None))
        self.comboBox_UnitCh6.setItemText(28, QCoreApplication.translate("DroidDAQ", u"mA", None))
        self.comboBox_UnitCh6.setItemText(29, QCoreApplication.translate("DroidDAQ", u"W", None))
        self.comboBox_UnitCh6.setItemText(30, QCoreApplication.translate("DroidDAQ", u"VA", None))
        self.comboBox_UnitCh6.setItemText(31, QCoreApplication.translate("DroidDAQ", u"VAR", None))
        self.comboBox_UnitCh6.setItemText(32, QCoreApplication.translate("DroidDAQ", u"kWh", None))

        self.comboBox_UnitCh6.setCurrentText(QCoreApplication.translate("DroidDAQ", u"N", None))
        self.comboBox_UnitCh2.setItemText(0, QCoreApplication.translate("DroidDAQ", u"N", None))
        self.comboBox_UnitCh2.setItemText(1, QCoreApplication.translate("DroidDAQ", u"kN", None))
        self.comboBox_UnitCh2.setItemText(2, QCoreApplication.translate("DroidDAQ", u"g", None))
        self.comboBox_UnitCh2.setItemText(3, QCoreApplication.translate("DroidDAQ", u"kg", None))
        self.comboBox_UnitCh2.setItemText(4, QCoreApplication.translate("DroidDAQ", u"ton", None))
        self.comboBox_UnitCh2.setItemText(5, QCoreApplication.translate("DroidDAQ", u"Pa", None))
        self.comboBox_UnitCh2.setItemText(6, QCoreApplication.translate("DroidDAQ", u"kPa", None))
        self.comboBox_UnitCh2.setItemText(7, QCoreApplication.translate("DroidDAQ", u"MPa", None))
        self.comboBox_UnitCh2.setItemText(8, QCoreApplication.translate("DroidDAQ", u"bar", None))
        self.comboBox_UnitCh2.setItemText(9, QCoreApplication.translate("DroidDAQ", u"mbar", None))
        self.comboBox_UnitCh2.setItemText(10, QCoreApplication.translate("DroidDAQ", u"psi", None))
        self.comboBox_UnitCh2.setItemText(11, QCoreApplication.translate("DroidDAQ", u"atm", None))
        self.comboBox_UnitCh2.setItemText(12, QCoreApplication.translate("DroidDAQ", u"m", None))
        self.comboBox_UnitCh2.setItemText(13, QCoreApplication.translate("DroidDAQ", u"cm", None))
        self.comboBox_UnitCh2.setItemText(14, QCoreApplication.translate("DroidDAQ", u"mm", None))
        self.comboBox_UnitCh2.setItemText(15, QCoreApplication.translate("DroidDAQ", u"\u03b5", None))
        self.comboBox_UnitCh2.setItemText(16, QCoreApplication.translate("DroidDAQ", u"\u00b5\u03b5", None))
        self.comboBox_UnitCh2.setItemText(17, QCoreApplication.translate("DroidDAQ", u"%", None))
        self.comboBox_UnitCh2.setItemText(18, QCoreApplication.translate("DroidDAQ", u"m/s", None))
        self.comboBox_UnitCh2.setItemText(19, QCoreApplication.translate("DroidDAQ", u"km/h", None))
        self.comboBox_UnitCh2.setItemText(20, QCoreApplication.translate("DroidDAQ", u"knots", None))
        self.comboBox_UnitCh2.setItemText(21, QCoreApplication.translate("DroidDAQ", u"RPM", None))
        self.comboBox_UnitCh2.setItemText(22, QCoreApplication.translate("DroidDAQ", u"rad/s", None))
        self.comboBox_UnitCh2.setItemText(23, QCoreApplication.translate("DroidDAQ", u"\u00b0/s", None))
        self.comboBox_UnitCh2.setItemText(24, QCoreApplication.translate("DroidDAQ", u"Hz", None))
        self.comboBox_UnitCh2.setItemText(25, QCoreApplication.translate("DroidDAQ", u"V", None))
        self.comboBox_UnitCh2.setItemText(26, QCoreApplication.translate("DroidDAQ", u"mV", None))
        self.comboBox_UnitCh2.setItemText(27, QCoreApplication.translate("DroidDAQ", u"A", None))
        self.comboBox_UnitCh2.setItemText(28, QCoreApplication.translate("DroidDAQ", u"mA", None))
        self.comboBox_UnitCh2.setItemText(29, QCoreApplication.translate("DroidDAQ", u"W", None))
        self.comboBox_UnitCh2.setItemText(30, QCoreApplication.translate("DroidDAQ", u"VA", None))
        self.comboBox_UnitCh2.setItemText(31, QCoreApplication.translate("DroidDAQ", u"VAR", None))
        self.comboBox_UnitCh2.setItemText(32, QCoreApplication.translate("DroidDAQ", u"kWh", None))

        self.comboBox_UnitCh2.setCurrentText(QCoreApplication.translate("DroidDAQ", u"N", None))
        self.comboBox_UnitCh5.setItemText(0, QCoreApplication.translate("DroidDAQ", u"N", None))
        self.comboBox_UnitCh5.setItemText(1, QCoreApplication.translate("DroidDAQ", u"kN", None))
        self.comboBox_UnitCh5.setItemText(2, QCoreApplication.translate("DroidDAQ", u"g", None))
        self.comboBox_UnitCh5.setItemText(3, QCoreApplication.translate("DroidDAQ", u"kg", None))
        self.comboBox_UnitCh5.setItemText(4, QCoreApplication.translate("DroidDAQ", u"ton", None))
        self.comboBox_UnitCh5.setItemText(5, QCoreApplication.translate("DroidDAQ", u"Pa", None))
        self.comboBox_UnitCh5.setItemText(6, QCoreApplication.translate("DroidDAQ", u"kPa", None))
        self.comboBox_UnitCh5.setItemText(7, QCoreApplication.translate("DroidDAQ", u"MPa", None))
        self.comboBox_UnitCh5.setItemText(8, QCoreApplication.translate("DroidDAQ", u"bar", None))
        self.comboBox_UnitCh5.setItemText(9, QCoreApplication.translate("DroidDAQ", u"mbar", None))
        self.comboBox_UnitCh5.setItemText(10, QCoreApplication.translate("DroidDAQ", u"psi", None))
        self.comboBox_UnitCh5.setItemText(11, QCoreApplication.translate("DroidDAQ", u"atm", None))
        self.comboBox_UnitCh5.setItemText(12, QCoreApplication.translate("DroidDAQ", u"m", None))
        self.comboBox_UnitCh5.setItemText(13, QCoreApplication.translate("DroidDAQ", u"cm", None))
        self.comboBox_UnitCh5.setItemText(14, QCoreApplication.translate("DroidDAQ", u"mm", None))
        self.comboBox_UnitCh5.setItemText(15, QCoreApplication.translate("DroidDAQ", u"\u03b5", None))
        self.comboBox_UnitCh5.setItemText(16, QCoreApplication.translate("DroidDAQ", u"\u00b5\u03b5", None))
        self.comboBox_UnitCh5.setItemText(17, QCoreApplication.translate("DroidDAQ", u"%", None))
        self.comboBox_UnitCh5.setItemText(18, QCoreApplication.translate("DroidDAQ", u"m/s", None))
        self.comboBox_UnitCh5.setItemText(19, QCoreApplication.translate("DroidDAQ", u"km/h", None))
        self.comboBox_UnitCh5.setItemText(20, QCoreApplication.translate("DroidDAQ", u"knots", None))
        self.comboBox_UnitCh5.setItemText(21, QCoreApplication.translate("DroidDAQ", u"RPM", None))
        self.comboBox_UnitCh5.setItemText(22, QCoreApplication.translate("DroidDAQ", u"rad/s", None))
        self.comboBox_UnitCh5.setItemText(23, QCoreApplication.translate("DroidDAQ", u"\u00b0/s", None))
        self.comboBox_UnitCh5.setItemText(24, QCoreApplication.translate("DroidDAQ", u"Hz", None))
        self.comboBox_UnitCh5.setItemText(25, QCoreApplication.translate("DroidDAQ", u"V", None))
        self.comboBox_UnitCh5.setItemText(26, QCoreApplication.translate("DroidDAQ", u"mV", None))
        self.comboBox_UnitCh5.setItemText(27, QCoreApplication.translate("DroidDAQ", u"A", None))
        self.comboBox_UnitCh5.setItemText(28, QCoreApplication.translate("DroidDAQ", u"mA", None))
        self.comboBox_UnitCh5.setItemText(29, QCoreApplication.translate("DroidDAQ", u"W", None))
        self.comboBox_UnitCh5.setItemText(30, QCoreApplication.translate("DroidDAQ", u"VA", None))
        self.comboBox_UnitCh5.setItemText(31, QCoreApplication.translate("DroidDAQ", u"VAR", None))
        self.comboBox_UnitCh5.setItemText(32, QCoreApplication.translate("DroidDAQ", u"kWh", None))

        self.comboBox_UnitCh5.setCurrentText(QCoreApplication.translate("DroidDAQ", u"N", None))
        self.comboBox_UnitCh3.setItemText(0, QCoreApplication.translate("DroidDAQ", u"N", None))
        self.comboBox_UnitCh3.setItemText(1, QCoreApplication.translate("DroidDAQ", u"kN", None))
        self.comboBox_UnitCh3.setItemText(2, QCoreApplication.translate("DroidDAQ", u"g", None))
        self.comboBox_UnitCh3.setItemText(3, QCoreApplication.translate("DroidDAQ", u"kg", None))
        self.comboBox_UnitCh3.setItemText(4, QCoreApplication.translate("DroidDAQ", u"ton", None))
        self.comboBox_UnitCh3.setItemText(5, QCoreApplication.translate("DroidDAQ", u"Pa", None))
        self.comboBox_UnitCh3.setItemText(6, QCoreApplication.translate("DroidDAQ", u"kPa", None))
        self.comboBox_UnitCh3.setItemText(7, QCoreApplication.translate("DroidDAQ", u"MPa", None))
        self.comboBox_UnitCh3.setItemText(8, QCoreApplication.translate("DroidDAQ", u"bar", None))
        self.comboBox_UnitCh3.setItemText(9, QCoreApplication.translate("DroidDAQ", u"mbar", None))
        self.comboBox_UnitCh3.setItemText(10, QCoreApplication.translate("DroidDAQ", u"psi", None))
        self.comboBox_UnitCh3.setItemText(11, QCoreApplication.translate("DroidDAQ", u"atm", None))
        self.comboBox_UnitCh3.setItemText(12, QCoreApplication.translate("DroidDAQ", u"m", None))
        self.comboBox_UnitCh3.setItemText(13, QCoreApplication.translate("DroidDAQ", u"cm", None))
        self.comboBox_UnitCh3.setItemText(14, QCoreApplication.translate("DroidDAQ", u"mm", None))
        self.comboBox_UnitCh3.setItemText(15, QCoreApplication.translate("DroidDAQ", u"\u03b5", None))
        self.comboBox_UnitCh3.setItemText(16, QCoreApplication.translate("DroidDAQ", u"\u00b5\u03b5", None))
        self.comboBox_UnitCh3.setItemText(17, QCoreApplication.translate("DroidDAQ", u"%", None))
        self.comboBox_UnitCh3.setItemText(18, QCoreApplication.translate("DroidDAQ", u"m/s", None))
        self.comboBox_UnitCh3.setItemText(19, QCoreApplication.translate("DroidDAQ", u"km/h", None))
        self.comboBox_UnitCh3.setItemText(20, QCoreApplication.translate("DroidDAQ", u"knots", None))
        self.comboBox_UnitCh3.setItemText(21, QCoreApplication.translate("DroidDAQ", u"RPM", None))
        self.comboBox_UnitCh3.setItemText(22, QCoreApplication.translate("DroidDAQ", u"rad/s", None))
        self.comboBox_UnitCh3.setItemText(23, QCoreApplication.translate("DroidDAQ", u"\u00b0/s", None))
        self.comboBox_UnitCh3.setItemText(24, QCoreApplication.translate("DroidDAQ", u"Hz", None))
        self.comboBox_UnitCh3.setItemText(25, QCoreApplication.translate("DroidDAQ", u"V", None))
        self.comboBox_UnitCh3.setItemText(26, QCoreApplication.translate("DroidDAQ", u"mV", None))
        self.comboBox_UnitCh3.setItemText(27, QCoreApplication.translate("DroidDAQ", u"A", None))
        self.comboBox_UnitCh3.setItemText(28, QCoreApplication.translate("DroidDAQ", u"mA", None))
        self.comboBox_UnitCh3.setItemText(29, QCoreApplication.translate("DroidDAQ", u"W", None))
        self.comboBox_UnitCh3.setItemText(30, QCoreApplication.translate("DroidDAQ", u"VA", None))
        self.comboBox_UnitCh3.setItemText(31, QCoreApplication.translate("DroidDAQ", u"VAR", None))
        self.comboBox_UnitCh3.setItemText(32, QCoreApplication.translate("DroidDAQ", u"kWh", None))

        self.comboBox_UnitCh3.setCurrentText(QCoreApplication.translate("DroidDAQ", u"N", None))
        self.comboBox_UnitCh4.setItemText(0, QCoreApplication.translate("DroidDAQ", u"N", None))
        self.comboBox_UnitCh4.setItemText(1, QCoreApplication.translate("DroidDAQ", u"kN", None))
        self.comboBox_UnitCh4.setItemText(2, QCoreApplication.translate("DroidDAQ", u"g", None))
        self.comboBox_UnitCh4.setItemText(3, QCoreApplication.translate("DroidDAQ", u"kg", None))
        self.comboBox_UnitCh4.setItemText(4, QCoreApplication.translate("DroidDAQ", u"ton", None))
        self.comboBox_UnitCh4.setItemText(5, QCoreApplication.translate("DroidDAQ", u"Pa", None))
        self.comboBox_UnitCh4.setItemText(6, QCoreApplication.translate("DroidDAQ", u"kPa", None))
        self.comboBox_UnitCh4.setItemText(7, QCoreApplication.translate("DroidDAQ", u"MPa", None))
        self.comboBox_UnitCh4.setItemText(8, QCoreApplication.translate("DroidDAQ", u"bar", None))
        self.comboBox_UnitCh4.setItemText(9, QCoreApplication.translate("DroidDAQ", u"mbar", None))
        self.comboBox_UnitCh4.setItemText(10, QCoreApplication.translate("DroidDAQ", u"psi", None))
        self.comboBox_UnitCh4.setItemText(11, QCoreApplication.translate("DroidDAQ", u"atm", None))
        self.comboBox_UnitCh4.setItemText(12, QCoreApplication.translate("DroidDAQ", u"m", None))
        self.comboBox_UnitCh4.setItemText(13, QCoreApplication.translate("DroidDAQ", u"cm", None))
        self.comboBox_UnitCh4.setItemText(14, QCoreApplication.translate("DroidDAQ", u"mm", None))
        self.comboBox_UnitCh4.setItemText(15, QCoreApplication.translate("DroidDAQ", u"\u03b5", None))
        self.comboBox_UnitCh4.setItemText(16, QCoreApplication.translate("DroidDAQ", u"\u00b5\u03b5", None))
        self.comboBox_UnitCh4.setItemText(17, QCoreApplication.translate("DroidDAQ", u"%", None))
        self.comboBox_UnitCh4.setItemText(18, QCoreApplication.translate("DroidDAQ", u"m/s", None))
        self.comboBox_UnitCh4.setItemText(19, QCoreApplication.translate("DroidDAQ", u"km/h", None))
        self.comboBox_UnitCh4.setItemText(20, QCoreApplication.translate("DroidDAQ", u"knots", None))
        self.comboBox_UnitCh4.setItemText(21, QCoreApplication.translate("DroidDAQ", u"RPM", None))
        self.comboBox_UnitCh4.setItemText(22, QCoreApplication.translate("DroidDAQ", u"rad/s", None))
        self.comboBox_UnitCh4.setItemText(23, QCoreApplication.translate("DroidDAQ", u"\u00b0/s", None))
        self.comboBox_UnitCh4.setItemText(24, QCoreApplication.translate("DroidDAQ", u"Hz", None))
        self.comboBox_UnitCh4.setItemText(25, QCoreApplication.translate("DroidDAQ", u"V", None))
        self.comboBox_UnitCh4.setItemText(26, QCoreApplication.translate("DroidDAQ", u"mV", None))
        self.comboBox_UnitCh4.setItemText(27, QCoreApplication.translate("DroidDAQ", u"A", None))
        self.comboBox_UnitCh4.setItemText(28, QCoreApplication.translate("DroidDAQ", u"mA", None))
        self.comboBox_UnitCh4.setItemText(29, QCoreApplication.translate("DroidDAQ", u"W", None))
        self.comboBox_UnitCh4.setItemText(30, QCoreApplication.translate("DroidDAQ", u"VA", None))
        self.comboBox_UnitCh4.setItemText(31, QCoreApplication.translate("DroidDAQ", u"VAR", None))
        self.comboBox_UnitCh4.setItemText(32, QCoreApplication.translate("DroidDAQ", u"kWh", None))

        self.comboBox_UnitCh4.setCurrentText(QCoreApplication.translate("DroidDAQ", u"N", None))
        self.comboBox_UnitCh7.setItemText(0, QCoreApplication.translate("DroidDAQ", u"N", None))
        self.comboBox_UnitCh7.setItemText(1, QCoreApplication.translate("DroidDAQ", u"kN", None))
        self.comboBox_UnitCh7.setItemText(2, QCoreApplication.translate("DroidDAQ", u"g", None))
        self.comboBox_UnitCh7.setItemText(3, QCoreApplication.translate("DroidDAQ", u"kg", None))
        self.comboBox_UnitCh7.setItemText(4, QCoreApplication.translate("DroidDAQ", u"ton", None))
        self.comboBox_UnitCh7.setItemText(5, QCoreApplication.translate("DroidDAQ", u"Pa", None))
        self.comboBox_UnitCh7.setItemText(6, QCoreApplication.translate("DroidDAQ", u"kPa", None))
        self.comboBox_UnitCh7.setItemText(7, QCoreApplication.translate("DroidDAQ", u"MPa", None))
        self.comboBox_UnitCh7.setItemText(8, QCoreApplication.translate("DroidDAQ", u"bar", None))
        self.comboBox_UnitCh7.setItemText(9, QCoreApplication.translate("DroidDAQ", u"mbar", None))
        self.comboBox_UnitCh7.setItemText(10, QCoreApplication.translate("DroidDAQ", u"psi", None))
        self.comboBox_UnitCh7.setItemText(11, QCoreApplication.translate("DroidDAQ", u"atm", None))
        self.comboBox_UnitCh7.setItemText(12, QCoreApplication.translate("DroidDAQ", u"m", None))
        self.comboBox_UnitCh7.setItemText(13, QCoreApplication.translate("DroidDAQ", u"cm", None))
        self.comboBox_UnitCh7.setItemText(14, QCoreApplication.translate("DroidDAQ", u"mm", None))
        self.comboBox_UnitCh7.setItemText(15, QCoreApplication.translate("DroidDAQ", u"\u03b5", None))
        self.comboBox_UnitCh7.setItemText(16, QCoreApplication.translate("DroidDAQ", u"\u00b5\u03b5", None))
        self.comboBox_UnitCh7.setItemText(17, QCoreApplication.translate("DroidDAQ", u"%", None))
        self.comboBox_UnitCh7.setItemText(18, QCoreApplication.translate("DroidDAQ", u"m/s", None))
        self.comboBox_UnitCh7.setItemText(19, QCoreApplication.translate("DroidDAQ", u"km/h", None))
        self.comboBox_UnitCh7.setItemText(20, QCoreApplication.translate("DroidDAQ", u"knots", None))
        self.comboBox_UnitCh7.setItemText(21, QCoreApplication.translate("DroidDAQ", u"RPM", None))
        self.comboBox_UnitCh7.setItemText(22, QCoreApplication.translate("DroidDAQ", u"rad/s", None))
        self.comboBox_UnitCh7.setItemText(23, QCoreApplication.translate("DroidDAQ", u"\u00b0/s", None))
        self.comboBox_UnitCh7.setItemText(24, QCoreApplication.translate("DroidDAQ", u"Hz", None))
        self.comboBox_UnitCh7.setItemText(25, QCoreApplication.translate("DroidDAQ", u"V", None))
        self.comboBox_UnitCh7.setItemText(26, QCoreApplication.translate("DroidDAQ", u"mV", None))
        self.comboBox_UnitCh7.setItemText(27, QCoreApplication.translate("DroidDAQ", u"A", None))
        self.comboBox_UnitCh7.setItemText(28, QCoreApplication.translate("DroidDAQ", u"mA", None))
        self.comboBox_UnitCh7.setItemText(29, QCoreApplication.translate("DroidDAQ", u"W", None))
        self.comboBox_UnitCh7.setItemText(30, QCoreApplication.translate("DroidDAQ", u"VA", None))
        self.comboBox_UnitCh7.setItemText(31, QCoreApplication.translate("DroidDAQ", u"VAR", None))
        self.comboBox_UnitCh7.setItemText(32, QCoreApplication.translate("DroidDAQ", u"kWh", None))

        self.comboBox_UnitCh7.setCurrentText(QCoreApplication.translate("DroidDAQ", u"N", None))
        self.comboBox_UnitCh1.setItemText(0, QCoreApplication.translate("DroidDAQ", u"N", None))
        self.comboBox_UnitCh1.setItemText(1, QCoreApplication.translate("DroidDAQ", u"kN", None))
        self.comboBox_UnitCh1.setItemText(2, QCoreApplication.translate("DroidDAQ", u"g", None))
        self.comboBox_UnitCh1.setItemText(3, QCoreApplication.translate("DroidDAQ", u"kg", None))
        self.comboBox_UnitCh1.setItemText(4, QCoreApplication.translate("DroidDAQ", u"ton", None))
        self.comboBox_UnitCh1.setItemText(5, QCoreApplication.translate("DroidDAQ", u"Pa", None))
        self.comboBox_UnitCh1.setItemText(6, QCoreApplication.translate("DroidDAQ", u"kPa", None))
        self.comboBox_UnitCh1.setItemText(7, QCoreApplication.translate("DroidDAQ", u"MPa", None))
        self.comboBox_UnitCh1.setItemText(8, QCoreApplication.translate("DroidDAQ", u"bar", None))
        self.comboBox_UnitCh1.setItemText(9, QCoreApplication.translate("DroidDAQ", u"mbar", None))
        self.comboBox_UnitCh1.setItemText(10, QCoreApplication.translate("DroidDAQ", u"psi", None))
        self.comboBox_UnitCh1.setItemText(11, QCoreApplication.translate("DroidDAQ", u"atm", None))
        self.comboBox_UnitCh1.setItemText(12, QCoreApplication.translate("DroidDAQ", u"m", None))
        self.comboBox_UnitCh1.setItemText(13, QCoreApplication.translate("DroidDAQ", u"cm", None))
        self.comboBox_UnitCh1.setItemText(14, QCoreApplication.translate("DroidDAQ", u"mm", None))
        self.comboBox_UnitCh1.setItemText(15, QCoreApplication.translate("DroidDAQ", u"\u03b5", None))
        self.comboBox_UnitCh1.setItemText(16, QCoreApplication.translate("DroidDAQ", u"\u00b5\u03b5", None))
        self.comboBox_UnitCh1.setItemText(17, QCoreApplication.translate("DroidDAQ", u"%", None))
        self.comboBox_UnitCh1.setItemText(18, QCoreApplication.translate("DroidDAQ", u"m/s", None))
        self.comboBox_UnitCh1.setItemText(19, QCoreApplication.translate("DroidDAQ", u"km/h", None))
        self.comboBox_UnitCh1.setItemText(20, QCoreApplication.translate("DroidDAQ", u"knots", None))
        self.comboBox_UnitCh1.setItemText(21, QCoreApplication.translate("DroidDAQ", u"RPM", None))
        self.comboBox_UnitCh1.setItemText(22, QCoreApplication.translate("DroidDAQ", u"rad/s", None))
        self.comboBox_UnitCh1.setItemText(23, QCoreApplication.translate("DroidDAQ", u"\u00b0/s", None))
        self.comboBox_UnitCh1.setItemText(24, QCoreApplication.translate("DroidDAQ", u"Hz", None))
        self.comboBox_UnitCh1.setItemText(25, QCoreApplication.translate("DroidDAQ", u"V", None))
        self.comboBox_UnitCh1.setItemText(26, QCoreApplication.translate("DroidDAQ", u"mV", None))
        self.comboBox_UnitCh1.setItemText(27, QCoreApplication.translate("DroidDAQ", u"A", None))
        self.comboBox_UnitCh1.setItemText(28, QCoreApplication.translate("DroidDAQ", u"mA", None))
        self.comboBox_UnitCh1.setItemText(29, QCoreApplication.translate("DroidDAQ", u"W", None))
        self.comboBox_UnitCh1.setItemText(30, QCoreApplication.translate("DroidDAQ", u"VA", None))
        self.comboBox_UnitCh1.setItemText(31, QCoreApplication.translate("DroidDAQ", u"VAR", None))
        self.comboBox_UnitCh1.setItemText(32, QCoreApplication.translate("DroidDAQ", u"kWh", None))

        self.comboBox_UnitCh1.setCurrentText(QCoreApplication.translate("DroidDAQ", u"N", None))
        self.lineEdit_NameCh3.setText(QCoreApplication.translate("DroidDAQ", u"Sens03", None))
        self.lineEdit_NameCh4.setText(QCoreApplication.translate("DroidDAQ", u"Senr04", None))
        self.lineEdit_NameCh5.setText(QCoreApplication.translate("DroidDAQ", u"Sens05", None))
        self.lineEdit_NameCh6.setText(QCoreApplication.translate("DroidDAQ", u"Sens06", None))
        self.lineEdit_NameCh7.setText(QCoreApplication.translate("DroidDAQ", u"Sens07", None))
        self.lineEdit_NameCh8.setText(QCoreApplication.translate("DroidDAQ", u"Sens08", None))
        self.lineEdit_CalCh1.setText(QCoreApplication.translate("DroidDAQ", u"calCH1_202603021021.txt", None))
        self.lineEdit_CalCh2.setText(QCoreApplication.translate("DroidDAQ", u"calCH2_202603021021.txt", None))
        self.lineEdit_CalCh3.setText(QCoreApplication.translate("DroidDAQ", u"calCH2_202603021021.txt", None))
        self.lineEdit_CalCh4.setText(QCoreApplication.translate("DroidDAQ", u"calCH2_202603021021.txt", None))
        self.lineEdit_CalCh5.setText(QCoreApplication.translate("DroidDAQ", u"calCH2_202603021021.txt", None))
        self.lineEdit_CalCh6.setText(QCoreApplication.translate("DroidDAQ", u"calCH2_202603021021.txt", None))
        self.lineEdit_CalCh7.setText(QCoreApplication.translate("DroidDAQ", u"calCH2_202603021021.txt", None))
        self.lineEdit_CalCh8.setText(QCoreApplication.translate("DroidDAQ", u"calCH2_202603021021.txt", None))
        self.label_3.setText(QCoreApplication.translate("DroidDAQ", u"CH1", None))
        self.label_6.setText(QCoreApplication.translate("DroidDAQ", u"CH2", None))
        self.label_7.setText(QCoreApplication.translate("DroidDAQ", u"CH3", None))
        self.label_8.setText(QCoreApplication.translate("DroidDAQ", u"CH4", None))
        self.label_9.setText(QCoreApplication.translate("DroidDAQ", u"CH5", None))
        self.label_10.setText(QCoreApplication.translate("DroidDAQ", u"CH6", None))
        self.label_11.setText(QCoreApplication.translate("DroidDAQ", u"CH7", None))
        self.label_12.setText(QCoreApplication.translate("DroidDAQ", u"CH8", None))
        self.label_13.setText(QCoreApplication.translate("DroidDAQ", u"Sensor Name", None))
        self.label_14.setText(QCoreApplication.translate("DroidDAQ", u"Calibration File", None))
        self.pushButton_BrwsCalCh1.setText(QCoreApplication.translate("DroidDAQ", u"Browse", None))
        self.pushButton_BrwsCalCh2.setText(QCoreApplication.translate("DroidDAQ", u"Browse", None))
        self.pushButton_BrwsCalCh3.setText(QCoreApplication.translate("DroidDAQ", u"Browse", None))
        self.pushButton_BrwsCalCh4.setText(QCoreApplication.translate("DroidDAQ", u"Browse", None))
        self.pushButton_BrwsCalCh5.setText(QCoreApplication.translate("DroidDAQ", u"Browse", None))
        self.pushButton_BrwsCalCh6.setText(QCoreApplication.translate("DroidDAQ", u"Browse", None))
        self.pushButton_BrwsCalCh7.setText(QCoreApplication.translate("DroidDAQ", u"Browse", None))
        self.pushButton_BrwsCalCh8.setText(QCoreApplication.translate("DroidDAQ", u"Browse", None))
        self.label_16.setText(QCoreApplication.translate("DroidDAQ", u"Unit", None))
        self.comboBox_ComPort.setItemText(0, QCoreApplication.translate("DroidDAQ", u"COM1", None))
        self.comboBox_ComPort.setItemText(1, QCoreApplication.translate("DroidDAQ", u"COM2", None))
        self.comboBox_ComPort.setItemText(2, QCoreApplication.translate("DroidDAQ", u"COM3", None))
        self.comboBox_ComPort.setItemText(3, QCoreApplication.translate("DroidDAQ", u"COM4", None))
        self.comboBox_ComPort.setItemText(4, QCoreApplication.translate("DroidDAQ", u"COM5", None))
        self.comboBox_ComPort.setItemText(5, QCoreApplication.translate("DroidDAQ", u"COM6", None))
        self.comboBox_ComPort.setItemText(6, QCoreApplication.translate("DroidDAQ", u"COM7", None))
        self.comboBox_ComPort.setItemText(7, QCoreApplication.translate("DroidDAQ", u"COM8", None))
        self.comboBox_ComPort.setItemText(8, QCoreApplication.translate("DroidDAQ", u"COM9", None))
        self.comboBox_ComPort.setItemText(9, QCoreApplication.translate("DroidDAQ", u"COM10", None))

        self.comboBox_ComPort.setCurrentText(QCoreApplication.translate("DroidDAQ", u"COM1", None))
        self.label_15.setText(QCoreApplication.translate("DroidDAQ", u"COM PORT DAQ", None))
        self.pushButton_ApplyConfig.setText(QCoreApplication.translate("DroidDAQ", u"Apply", None))
        self.comboBox_FreqSampl.setItemText(0, QCoreApplication.translate("DroidDAQ", u"10", None))
        self.comboBox_FreqSampl.setItemText(1, QCoreApplication.translate("DroidDAQ", u"20", None))
        self.comboBox_FreqSampl.setItemText(2, QCoreApplication.translate("DroidDAQ", u"30", None))
        self.comboBox_FreqSampl.setItemText(3, QCoreApplication.translate("DroidDAQ", u"40", None))
        self.comboBox_FreqSampl.setItemText(4, QCoreApplication.translate("DroidDAQ", u"50", None))
        self.comboBox_FreqSampl.setItemText(5, QCoreApplication.translate("DroidDAQ", u"60", None))
        self.comboBox_FreqSampl.setItemText(6, QCoreApplication.translate("DroidDAQ", u"70", None))
        self.comboBox_FreqSampl.setItemText(7, QCoreApplication.translate("DroidDAQ", u"80", None))
        self.comboBox_FreqSampl.setItemText(8, QCoreApplication.translate("DroidDAQ", u"90", None))
        self.comboBox_FreqSampl.setItemText(9, QCoreApplication.translate("DroidDAQ", u"100", None))
        self.comboBox_FreqSampl.setItemText(10, QCoreApplication.translate("DroidDAQ", u"1000", None))

        self.comboBox_FreqSampl.setCurrentText(QCoreApplication.translate("DroidDAQ", u"10", None))
        self.label_17.setText(QCoreApplication.translate("DroidDAQ", u"Frequency Sampling (Hz)", None))
        self.pushButton_Scan.setText(QCoreApplication.translate("DroidDAQ", u"SCAN", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("DroidDAQ", u"Config", None))
        self.groupBoxSensorA.setTitle(QCoreApplication.translate("DroidDAQ", u"SENSOR", None))
        self.checkBox_Ch1.setText("")
        self.label_NameCh1.setText(QCoreApplication.translate("DroidDAQ", u"Sensor01", None))
        self.checkBox_Ch2.setText("")
        self.label_NameCh2.setText(QCoreApplication.translate("DroidDAQ", u"Sensor02", None))
        self.checkBox_Ch3.setText("")
        self.label_NameCh3.setText(QCoreApplication.translate("DroidDAQ", u"Sensor03", None))
        self.checkBox_Ch4.setText("")
        self.label_NameCh4.setText(QCoreApplication.translate("DroidDAQ", u"Sensor04", None))
        self.label_UnitCh01.setText(QCoreApplication.translate("DroidDAQ", u"kPa", None))
        self.label_UnitCh02.setText(QCoreApplication.translate("DroidDAQ", u"kPa", None))
        self.label_UnitCh03.setText(QCoreApplication.translate("DroidDAQ", u"kPa", None))
        self.label_UnitCh04.setText(QCoreApplication.translate("DroidDAQ", u"kPa", None))
        self.label_UnitCh05.setText(QCoreApplication.translate("DroidDAQ", u"kPa", None))
        self.checkBox_Ch5.setText("")
        self.label_NameCh5.setText(QCoreApplication.translate("DroidDAQ", u"Sensor05", None))
        self.label_UnitCh06.setText(QCoreApplication.translate("DroidDAQ", u"kPa", None))
        self.checkBox_Ch6.setText("")
        self.label_NameCh6.setText(QCoreApplication.translate("DroidDAQ", u"Sensor06", None))
        self.checkBox_Ch7.setText("")
        self.label_NameCh7.setText(QCoreApplication.translate("DroidDAQ", u"Sensor07", None))
        self.label_UnitCh07.setText(QCoreApplication.translate("DroidDAQ", u"kPa", None))
        self.label_UnitCh08.setText(QCoreApplication.translate("DroidDAQ", u"kPa", None))
        self.checkBox_Ch8.setText("")
        self.label_NameCh8.setText(QCoreApplication.translate("DroidDAQ", u"Sensor08", None))
        self.label_2.setText(QCoreApplication.translate("DroidDAQ", u"DroidDAQ", None))
        self.pushButton_Connect.setText(QCoreApplication.translate("DroidDAQ", u"CONNECT", None))
        self.groupBox.setTitle(QCoreApplication.translate("DroidDAQ", u"RECORD", None))
        self.label.setText(QCoreApplication.translate("DroidDAQ", u"Test Name", None))
        self.label_4.setText(QCoreApplication.translate("DroidDAQ", u"Folder ", None))
        self.label_5.setText(QCoreApplication.translate("DroidDAQ", u"Duration (s)", None))
        self.pushButton_TestBrowse.setText(QCoreApplication.translate("DroidDAQ", u"Browse", None))
        self.pushButton_StartRecord.setText(QCoreApplication.translate("DroidDAQ", u"START", None))
        self.pushButton_STOP.setText(QCoreApplication.translate("DroidDAQ", u"STOP", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DataAcquisition), QCoreApplication.translate("DroidDAQ", u"Data Acquisition", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Calibration), QCoreApplication.translate("DroidDAQ", u"Calibration", None))
    # retranslateUi

